version: '3.8'

services:
  scylla:
    image: scylladb/scylla:5.2
    container_name: scylla-search
    ports:
      - "9043:9042"
    environment:
      - SCYLLA_CLUSTER_NAME=search-cluster
      - SCYLLA_DC=datacenter1
      - SCYLLA_RACK=rack1
    volumes:
      - scylla-data:/var/lib/scylla
    command: --seeds=scylla --smp 1 --memory 2G --overprovisioned 1 --developer-mode=1
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep UN"]
      interval: 10s
      timeout: 5s
      retries: 12
    networks:
      - async-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch-search
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - cluster.routing.allocation.disk.watermark.low=85%
      - cluster.routing.allocation.disk.watermark.high=90%
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - scylla
    networks:
      - async-network

volumes:
  scylla-data:
  elasticsearch-data:

networks:
  async-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16