spring:
  profiles: prod

scylla:
  contact-points: ${SCYLLA_HOSTS:scylla-cluster}
  port: ${SCYLLA_PORT:9042}
  keyspace: ${SCYLLA_KEYSPACE:search_data}
  datacenter: ${SCYLLA_DATACENTER:datacenter1}

elasticsearch:
  host: ${ELASTICSEARCH_HOST:elasticsearch-cluster}
  port: ${ELASTICSEARCH_PORT:9200}
  scheme: ${ELASTICSEARCH_SCHEME:http}

logging:
  level:
    com.company.search: INFO
    root: WARN